version: '3'
services:
  processor-template:
    image: processor-template:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - api.env
    network_mode: "host"
